export declare const button: string;
export declare const container: string;
export declare const header: string;
export declare const navbar: string;
export declare const right: string;
export declare const search: string;
export declare const searchBox: string;
export declare const topHeader: string;
export declare const topHeaderContent: string;
